# My action

name: 'Hello World action'
description: 'Saludar ya'
inputs:
  title-regex:
    description: 'Title regex to match'
    required: true
    default: '^\[PROJECT-\d*\]\ '
outputs:
  time: #id of output
    description: 'the time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'
