# My action

name: 'Pull request title Validator'
description: 'This github action validates pull requests title with regex'
inputs:
  title-regex:
    description: 'Title regex to match'
    required: true
    default: '^\[PROJECT-\d*\]\ '
  error-message:
    description: 'Description message as input'
    required: true
    default: '^\[PROJECT-\d*\]\ '
outputs:
  message: #id of output
    description: 'output message'
runs:
  using: 'node12'
  main: 'index.js'
