

name: JIRA Validation

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  hellow_world_job:
    runs-on: ubuntu-latest
    name: Pull request title validation
    steps:
      - name: Hello world actions steps
        id: hello
        uses: richimf/MyGithubActionDemo@v6
        with:
          title-regex: '^(?:\[IMPROVEMENT\]|\[FEATURE\]|\[BUGFIX\])\[([A-Z])+\-(\d+)\]\s(\w){1,}(\w|\s|\-){1,}$'
      # Use the output from the 'hello' step
      - name: Get the output
        run: echo "OUTPUT $${{ steps.hello.outputs.message }}"


